# Generated by Django 5.1.4 on 2024-12-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado')], default='libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_det', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad', to='licoreria.local')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Productos', to='licoreria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='licoreria.tipo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_det_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_ventas', to='licoreria.detalle')),
            ],
        ),
    ]
